import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import * as schema from "./schema/index.js";
import {
  booksTable,
  offersTable,
  authorAdsTable,
} from "./schema/index.js";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool, { schema });

async function seed() {
  console.log("Seeding database...");

  const existingBooks = await db.select({ id: booksTable.id }).from(booksTable).limit(1);
  if (existingBooks.length > 0) {
    console.log("Database already seeded. Skipping.");
    await pool.end();
    return;
  }

  await db.insert(booksTable).values([
    {
      title: "Bangla Grammar",
      titleBn: "বাংলা ব্যাকরণ ও নির্মিতি",
      author: "Dr. Harun-or-Rashid",
      authorBn: "ড. হারুন-অর-রশিদ",
      publisher: "NCTB",
      publisherBn: "এনসিটিবি",
      price: "120",
      discountedPrice: "100",
      category: "school-class6",
      coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
      descriptionBn: "ষষ্ঠ শ্রেণির বাংলা ব্যাকরণ বই। ব্যাকরণের মূল নিয়মাবলি সুন্দরভাবে উপস্থাপন করা হয়েছে।",
      previewTextBn: "বাংলা ভাষার উৎপত্তি হয়েছে সংস্কৃত ভাষা থেকে। ইন্দো-ইউরোপীয় ভাষাগোষ্ঠীর অন্তর্গত এই ভাষা...",
      stockCount: 50,
      rating: "4.5",
      reviewCount: 120,
      isFeatured: true,
    },
    {
      title: "Mathematics",
      titleBn: "গণিত (সপ্তম শ্রেণি)",
      author: "NCTB",
      authorBn: "এনসিটিবি",
      publisher: "NCTB",
      publisherBn: "এনসিটিবি",
      price: "150",
      discountedPrice: "130",
      category: "school-class7",
      coverImage: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=300&h=400&fit=crop",
      descriptionBn: "সপ্তম শ্রেণির গণিত বই। বীজগণিত, জ্যামিতি সহ সকল অধ্যায় অন্তর্ভুক্ত।",
      previewTextBn: "গণিত হলো বিজ্ঞান ও প্রযুক্তির ভিত্তি। এই বইতে সংখ্যা, বীজগণিত, জ্যামিতি...",
      stockCount: 45,
      rating: "4.3",
      reviewCount: 89,
      isFeatured: true,
    },
    {
      title: "Science",
      titleBn: "বিজ্ঞান (অষ্টম শ্রেণি)",
      author: "NCTB",
      authorBn: "এনসিটিবি",
      publisher: "NCTB",
      publisherBn: "এনসিটিবি",
      price: "140",
      discountedPrice: "115",
      category: "school-class8",
      coverImage: "https://images.unsplash.com/photo-1532094349884-543559059088?w=300&h=400&fit=crop",
      descriptionBn: "অষ্টম শ্রেণির বিজ্ঞান বই। পদার্থ, রসায়ন, জীববিজ্ঞান সহ বিভিন্ন বিষয় আলোচিত।",
      previewTextBn: "পদার্থের তিনটি অবস্থা আছে - কঠিন, তরল এবং বায়বীয়। এই বইতে আমরা...",
      stockCount: 60,
      rating: "4.6",
      reviewCount: 200,
      isFeatured: true,
    },
    {
      title: "English Grammar (Old)",
      titleBn: "ইংরেজি ব্যাকরণ (পুরাতন)",
      author: "Various Authors",
      authorBn: "বিভিন্ন লেখক",
      publisher: "Old Edition",
      publisherBn: "পুরাতন সংস্করণ",
      price: "80",
      discountedPrice: "60",
      category: "school-class8",
      coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop",
      descriptionBn: "পুরাতন ইংরেজি ব্যাকরণ বই। ভালো অবস্থায় আছে।",
      previewTextBn: "English grammar is the set of structural rules of the English language...",
      stockCount: 20,
      rating: "3.8",
      reviewCount: 45,
      isFeatured: false,
    },
    {
      title: "Higher Mathematics",
      titleBn: "উচ্চতর গণিত (প্রথম পত্র)",
      author: "Abdul Mannan",
      authorBn: "আব্দুল মান্নান",
      publisher: "Hasan Book House",
      publisherBn: "হাসান বুক হাউস",
      price: "280",
      discountedPrice: "250",
      category: "college-science",
      coverImage: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=300&h=400&fit=crop",
      descriptionBn: "এইচএসসি প্রথম বর্ষের উচ্চতর গণিত। ক্যালকুলাস, ভেক্টর, ত্রিকোণমিতি সহ সকল অধ্যায়।",
      previewTextBn: "উচ্চতর গণিতের প্রথম অধ্যায়ে আমরা ভেক্টর নিয়ে আলোচনা করব। ভেক্টর হলো এমন রাশি...",
      stockCount: 80,
      rating: "4.7",
      reviewCount: 340,
      isFeatured: true,
    },
    {
      title: "Physics 1st Paper",
      titleBn: "পদার্থবিজ্ঞান প্রথম পত্র",
      author: "Dr. Shahjahan Tapan",
      authorBn: "ড. শাহজাহান তপন",
      publisher: "Hasan Book House",
      publisherBn: "হাসান বুক হাউস",
      price: "320",
      discountedPrice: "280",
      category: "college-science",
      coverImage: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=300&h=400&fit=crop",
      descriptionBn: "এইচএসসি প্রথম বর্ষের পদার্থবিজ্ঞান। ভেক্টর, গতিবিদ্যা, কাজ-শক্তি সহ বিস্তারিত আলোচনা।",
      previewTextBn: "পদার্থবিজ্ঞান হলো প্রকৃতির মৌলিক নিয়মকানুন নিয়ে গবেষণার বিজ্ঞান। প্রথম অধ্যায়ে...",
      stockCount: 70,
      rating: "4.8",
      reviewCount: 420,
      isFeatured: true,
    },
    {
      title: "Chemistry (Old)",
      titleBn: "রসায়ন বিজ্ঞান (পুরাতন)",
      author: "Prof. Hossain",
      authorBn: "প্রফেসর হোসেন",
      publisher: "Old Edition",
      publisherBn: "পুরাতন সংস্করণ",
      price: "200",
      discountedPrice: "150",
      category: "college-science",
      coverImage: "https://images.unsplash.com/photo-1532094349884-543559059088?w=300&h=400&fit=crop",
      descriptionBn: "পুরাতন রসায়ন বিজ্ঞান বই। এইচএসসি স্তরের।",
      previewTextBn: "রসায়ন বিজ্ঞান পদার্থের গঠন, বৈশিষ্ট্য এবং পরিবর্তন নিয়ে আলোচনা করে...",
      stockCount: 15,
      rating: "4.0",
      reviewCount: 60,
      isFeatured: false,
    },
    {
      title: "University Admission Guide",
      titleBn: "বিশ্ববিদ্যালয় ভর্তি গাইড",
      author: "Prof. Team",
      authorBn: "প্রফেসর দল",
      publisher: "Admission Publications",
      publisherBn: "অ্যাডমিশন পাবলিকেশন্স",
      price: "500",
      discountedPrice: "450",
      category: "degree-year1",
      coverImage: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=300&h=400&fit=crop",
      descriptionBn: "বিশ্ববিদ্যালয় ভর্তি পরীক্ষার সম্পূর্ণ গাইড। বাংলা, ইংরেজি, গণিত, সাধারণ জ্ঞান সহ।",
      previewTextBn: "বিশ্ববিদ্যালয়ে ভর্তি হওয়া প্রতিটি শিক্ষার্থীর স্বপ্ন। এই গাইডটি...",
      stockCount: 100,
      rating: "4.5",
      reviewCount: 280,
      isFeatured: false,
    },
    {
      title: "BCS Preliminary",
      titleBn: "বিসিএস প্রিলিমিনারি গাইড",
      author: "Professor's",
      authorBn: "প্রফেসর'স",
      publisher: "Professor's Publications",
      publisherBn: "প্রফেসর'স পাবলিকেশন্স",
      price: "450",
      discountedPrice: "400",
      category: "job",
      coverImage: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=300&h=400&fit=crop",
      descriptionBn: "বিসিএস প্রিলিমিনারি পরীক্ষার জন্য সম্পূর্ণ গাইড। সকল বিষয় অন্তর্ভুক্ত।",
      previewTextBn: "বিসিএস পরীক্ষায় বাংলাদেশ বিষয়াবলি, আন্তর্জাতিক বিষয়াবলি, বাংলা, ইংরেজি...",
      stockCount: 120,
      rating: "4.9",
      reviewCount: 850,
      isFeatured: true,
    },
    {
      title: "Bank Job Guide",
      titleBn: "ব্যাংক জব গাইড",
      author: "Agami Publications",
      authorBn: "আগামী পাবলিকেশন্স",
      publisher: "Agami",
      publisherBn: "আগামী",
      price: "380",
      discountedPrice: "340",
      category: "job",
      coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop",
      descriptionBn: "ব্যাংক নিয়োগ পরীক্ষার জন্য সম্পূর্ণ গাইড।",
      previewTextBn: "ব্যাংক চাকরির পরীক্ষায় গণিত, ইংরেজি এবং সাধারণ জ্ঞান থেকে প্রশ্ন আসে...",
      stockCount: 90,
      rating: "4.6",
      reviewCount: 320,
      isFeatured: false,
    },
    {
      title: "Lalsalu",
      titleBn: "লালসালু",
      author: "Syed Waliullah",
      authorBn: "সৈয়দ ওয়ালীউল্লাহ",
      publisher: "Nawroz Kitabistan",
      publisherBn: "নওরোজ কিতাবিস্তান",
      price: "200",
      discountedPrice: "175",
      category: "novel",
      coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop",
      descriptionBn: "বাংলাদেশের অন্যতম শ্রেষ্ঠ উপন্যাস। গ্রামীণ সমাজের ধর্মীয় কুসংস্কার নিয়ে রচিত।",
      previewTextBn: "মজিদ এসেছিল ধানের ক্ষেতের মধ্য দিয়ে সরু পথটা ধরে। সেই পথ ঢলের জলে...",
      stockCount: 35,
      rating: "4.8",
      reviewCount: 560,
      isFeatured: true,
    },
    {
      title: "Padma Nadir Majhi",
      titleBn: "পদ্মা নদীর মাঝি",
      author: "Manik Bandopadhyay",
      authorBn: "মানিক বন্দ্যোপাধ্যায়",
      publisher: "Ananya",
      publisherBn: "অনন্যা",
      price: "220",
      discountedPrice: "190",
      category: "novel",
      coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop",
      descriptionBn: "পদ্মা নদীর মাঝি - বাংলা সাহিত্যের একটি অনবদ্য উপন্যাস।",
      previewTextBn: "পদ্মার তীরে জেলে পল্লীর জীবন নিয়ে লেখা এই উপন্যাসে হোসেন মিয়া...",
      stockCount: 40,
      rating: "4.7",
      reviewCount: 480,
      isFeatured: true,
    },
    {
      title: "Kobita Samagra",
      titleBn: "কবিতা সমগ্র - রবীন্দ্রনাথ",
      author: "Rabindranath Tagore",
      authorBn: "রবীন্দ্রনাথ ঠাকুর",
      publisher: "Ananya",
      publisherBn: "অনন্যা",
      price: "350",
      discountedPrice: "300",
      category: "story-poem",
      coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
      descriptionBn: "রবীন্দ্রনাথ ঠাকুরের সম্পূর্ণ কবিতা সংকলন।",
      previewTextBn: "আমার সোনার বাংলা, আমি তোমায় ভালোবাসি। চিরদিন তোমার আকাশ তোমার বাতাস...",
      stockCount: 55,
      rating: "5.0",
      reviewCount: 890,
      isFeatured: false,
    },
    {
      title: "Golpo Samagra",
      titleBn: "ছোট গল্প সংকলন - রবীন্দ্রনাথ",
      author: "Rabindranath Tagore",
      authorBn: "রবীন্দ্রনাথ ঠাকুর",
      publisher: "Ananya",
      publisherBn: "অনন্যা",
      price: "280",
      discountedPrice: "240",
      category: "story-poem",
      coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop",
      descriptionBn: "রবীন্দ্রনাথের বিখ্যাত ছোটগল্পের সংকলন।",
      previewTextBn: "মেঘের পালে আঁকা ছবির মতো ভেসে চলে জীবনের গল্প...",
      stockCount: 45,
      rating: "4.9",
      reviewCount: 650,
      isFeatured: false,
    },
  ]);

  await db.insert(offersTable).values([
    {
      titleBn: "ঈদ স্পেশাল অফার",
      descriptionBn: "সকল স্কুল বইয়ে ১৫% ছাড়। এই সুযোগ সীমিত সময়ের জন্য।",
      discountPercent: 15,
      startDate: new Date("2026-01-01"),
      endDate: new Date("2026-05-12"),
      isActive: true,
      badgeText: "ঈদ অফার",
      category: "school-class6",
    },
    {
      titleBn: "পুরাতন বই মেলা",
      descriptionBn: "পুরাতন বইয়ে ২০% বিশেষ ছাড়। ভালো বই কম দামে।",
      discountPercent: 20,
      startDate: new Date("2026-01-01"),
      endDate: new Date("2026-04-27"),
      isActive: true,
      badgeText: "মেলা অফার",
      category: "school-class8",
    },
    {
      titleBn: "চাকরি বই প্যাকেজ",
      descriptionBn: "যেকোনো ৩টি চাকরির বই কিনলে ২৫% ছাড়।",
      discountPercent: 25,
      startDate: new Date("2026-01-01"),
      endDate: new Date("2026-05-02"),
      isActive: true,
      badgeText: "প্যাকেজ ডিল",
      category: "job",
    },
    {
      titleBn: "গ্রীষ্মকালীন সেল",
      descriptionBn: "সকল উপন্যাস ও সাহিত্য বইয়ে ১০% ছাড়।",
      discountPercent: 10,
      startDate: new Date("2026-01-01"),
      endDate: new Date("2026-04-22"),
      isActive: true,
      badgeText: "সেল",
      category: "novel",
    },
  ]);

  await db.insert(authorAdsTable).values([
    {
      authorName: "Karim Hossain",
      mobile: "01712345678",
      email: "karim@example.com",
      bookTitle: "মুক্তির গান",
      bookDescription: "মুক্তিযুদ্ধের পটভূমিতে রচিত একটি আবেগময় উপন্যাস। ১৯৭১ সালের বীরত্বের গল্প।",
      genre: "novel",
      publisherName: "নতুন ধারা প্রকাশন",
      publishYear: 2024,
      price: "350",
      status: "approved",
    },
    {
      authorName: "Rina Begum",
      mobile: "01898765432",
      bookTitle: "আলোর পথে",
      bookDescription: "সামাজিক উপন্যাস। গ্রামীণ নারীর জীবনসংগ্রাম ও অগ্রগতির গল্প।",
      genre: "novel",
      publishYear: 2025,
      price: "280",
      status: "approved",
    },
    {
      authorName: "Sohel Rana",
      mobile: "01512345678",
      bookTitle: "পল্লীর কথা",
      bookDescription: "গ্রামীণ জীবনের সরল সুন্দর গল্পের সংকলন। প্রকৃতি ও মানুষের মেলবন্ধন।",
      genre: "story-poem",
      publishYear: 2025,
      price: "200",
      status: "approved",
    },
  ]);

  console.log("Database seeded successfully!");
  await pool.end();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
